### ISSUE TITLE
語尾は「なのだ」になりますか？（要議論）

### ISSUE THREAD

**Issue by anbara** [ShotaAk/robocup-ssl-voice-referee#1]

**Comment by ShotaAk** [comment]
レフェリー信号に合わせてどんなメッセージを話すのかは、speech_scripts内のyamlファイルで定義しています。

語尾を変えることも可能です。

ただし、デフォルトのメッセージには一般的な日本語を使用したいため、「なのだ」を採用する予定はありませんなのだ。

**Comment by anbara** [comment]
回答ありがとうございます．
明確な理由があって「なのだ」を採用していないようですので，そのままで良いと思いました．
欲しくなったらフォークするなのだ．
ありがとうございました．
